/**
 * Deterministic academic insight engine (Stage 4). Converts the analytics
 * models into a small number of prioritized, explainable observations —
 * never generated by a model, never random, always traceable to specific
 * recorded numbers via each insight's `evidence` string.
 *
 * Rules are deliberately few and bounded (never one rule per course per
 * dimension) so the result is naturally never a flood: each rule
 * contributes at most one insight, picking the single most notable course
 * when a rule is comparative. Language stays factual and neutral — no
 * "at risk," no predictions, no causal claims (PRODUCT_SPEC.md §13).
 */
import type { SemesterAnalytics } from "./semesterAnalytics";
import type { CourseAnalyticsProfile } from "./courseAnalytics";
import type { Trend } from "./trend";

export type InsightCategory =
  | "onboarding"
  | "overdue"
  | "task-completion"
  | "grade-level"
  | "trend-decline"
  | "trend-improve"
  | "consistency"
  | "trend-data";

export type InsightSeverity = "attention" | "positive" | "info";

export interface Insight {
  id: string;
  category: InsightCategory;
  severity: InsightSeverity;
  courseId?: string;
  message: string;
  /** Human-readable supporting numbers — what a student could check to
   * verify the insight themselves. */
  evidence: string;
}

const SEVERITY_RANK: Record<InsightSeverity, number> = { attention: 3, positive: 2, info: 1 };

// Documented thresholds — deliberately explicit, not tuned invisibly.
const MIN_TASKS_FOR_COURSE_INSIGHT = 3;
const LOW_COMPLETION_THRESHOLD = 60;
const MIN_TASKS_FOR_CONSISTENCY = 5;
const HIGH_CONSISTENCY_THRESHOLD = 90;
const MIN_GRADE_ENTRIES_FOR_COURSE_INSIGHT = 2;
const LOW_GRADE_THRESHOLD = 70;
const HIGH_GRADE_THRESHOLD = 85;

function round1(value: number): number {
  return Math.round(value * 10) / 10;
}

function hasAnyData(semester: SemesterAnalytics): boolean {
  return (
    semester.tasks.totalRelevant > 0 ||
    semester.attendance.attended + semester.attendance.missed > 0 ||
    semester.grades.entryCount > 0 ||
    semester.practice.entryCount > 0
  );
}

function weakestTaskCompletion(
  courses: CourseAnalyticsProfile[],
): CourseAnalyticsProfile | undefined {
  const eligible = courses.filter(
    (c) =>
      c.tasks.totalRelevant >= MIN_TASKS_FOR_COURSE_INSIGHT && c.tasks.completionRate !== undefined,
  );
  if (eligible.length === 0) return undefined;
  return eligible.reduce((worst, c) =>
    c.tasks.completionRate! < worst.tasks.completionRate! ? c : worst,
  );
}

function extremeGradeCourse(
  courses: CourseAnalyticsProfile[],
  direction: "lowest" | "highest",
): CourseAnalyticsProfile | undefined {
  const eligible = courses.filter(
    (c) =>
      c.grades.entryCount >= MIN_GRADE_ENTRIES_FOR_COURSE_INSIGHT &&
      c.grades.performancePercent !== undefined,
  );
  if (eligible.length === 0) return undefined;
  return eligible.reduce((extreme, c) => {
    const better =
      direction === "lowest"
        ? c.grades.performancePercent! < extreme.grades.performancePercent!
        : c.grades.performancePercent! > extreme.grades.performancePercent!;
    return better ? c : extreme;
  });
}

interface TrendCandidate {
  course: CourseAnalyticsProfile;
  dimension: "attendance" | "grades" | "practice";
  trend: Trend;
  delta: number;
}

function allTrendCandidates(courses: CourseAnalyticsProfile[]): TrendCandidate[] {
  const candidates: TrendCandidate[] = [];
  for (const course of courses) {
    for (const dimension of ["attendance", "grades", "practice"] as const) {
      const result = course[dimension].trend;
      if (result.delta === undefined) continue;
      candidates.push({ course, dimension, trend: result.trend, delta: result.delta });
    }
  }
  return candidates;
}

function dimensionLabel(dimension: "attendance" | "grades" | "practice"): string {
  return dimension === "attendance" ? "attendance" : dimension === "grades" ? "grade" : "practice";
}

/** Generates every applicable insight, already sorted most-important
 * first. Callers slice to however many they want to display (Home: 1,
 * Performance: several) — the ranking itself never changes based on how
 * many will be shown. */
export function generateInsights(semester: SemesterAnalytics): Insight[] {
  const insights: Insight[] = [];

  if (!hasAnyData(semester)) {
    return [
      {
        id: "onboarding",
        category: "onboarding",
        severity: "info",
        message: "Add tasks, attendance, or grades to start seeing insights here.",
        evidence: "No academic activity recorded yet this semester.",
      },
    ];
  }

  if (semester.tasks.overdueCount > 0) {
    insights.push({
      id: "overdue",
      category: "overdue",
      severity: "attention",
      message: `You have ${semester.tasks.overdueCount} overdue ${semester.tasks.overdueCount === 1 ? "task" : "tasks"}.`,
      evidence: `${semester.tasks.overdueCount} incomplete ${semester.tasks.overdueCount === 1 ? "task has" : "tasks have"} a due date in the past.`,
    });
  }

  const weakestTasks = weakestTaskCompletion(semester.courses);
  if (weakestTasks && weakestTasks.tasks.completionRate! < LOW_COMPLETION_THRESHOLD) {
    insights.push({
      id: `task-completion-${weakestTasks.course.id}`,
      category: "task-completion",
      severity: "attention",
      courseId: weakestTasks.course.id,
      message: `"${weakestTasks.course.name}" has your lowest task completion rate.`,
      evidence: `${weakestTasks.tasks.completed} of ${weakestTasks.tasks.totalRelevant} tasks completed (${round1(weakestTasks.tasks.completionRate!)}%).`,
    });
  }

  const weakestGrades = extremeGradeCourse(semester.courses, "lowest");
  if (weakestGrades && weakestGrades.grades.performancePercent! < LOW_GRADE_THRESHOLD) {
    insights.push({
      id: `grade-low-${weakestGrades.course.id}`,
      category: "grade-level",
      severity: "attention",
      courseId: weakestGrades.course.id,
      message: `"${weakestGrades.course.name}" currently has your weakest recorded grade performance.`,
      evidence: `${weakestGrades.grades.recordedEarned}/${weakestGrades.grades.recordedMax} recorded (${round1(weakestGrades.grades.performancePercent!)}%).`,
    });
  }

  const declining = allTrendCandidates(semester.courses)
    .filter((c) => c.trend === "declining")
    .sort((a, b) => a.delta - b.delta)[0];
  if (declining) {
    insights.push({
      id: `trend-decline-${declining.course.course.id}-${declining.dimension}`,
      category: "trend-decline",
      severity: "attention",
      courseId: declining.course.course.id,
      message: `${dimensionLabel(declining.dimension) === "attendance" ? "Attendance" : declining.dimension === "grades" ? "Grade performance" : "Practice performance"} in "${declining.course.course.name}" has declined across recent recorded ${declining.dimension === "attendance" ? "sessions" : "entries"}.`,
      evidence: `Recent average ${round1(declining.delta)} points lower than the earlier recorded average.`,
    });
  }

  const strongestGrades = extremeGradeCourse(semester.courses, "highest");
  if (strongestGrades && strongestGrades.grades.performancePercent! >= HIGH_GRADE_THRESHOLD) {
    insights.push({
      id: `grade-high-${strongestGrades.course.id}`,
      category: "grade-level",
      severity: "positive",
      courseId: strongestGrades.course.id,
      message: `"${strongestGrades.course.name}" currently has your strongest recorded grade performance.`,
      evidence: `${strongestGrades.grades.recordedEarned}/${strongestGrades.grades.recordedMax} recorded (${round1(strongestGrades.grades.performancePercent!)}%).`,
    });
  }

  const improving = allTrendCandidates(semester.courses)
    .filter((c) => c.trend === "improving")
    .sort((a, b) => b.delta - a.delta)[0];
  if (improving) {
    insights.push({
      id: `trend-improve-${improving.course.course.id}-${improving.dimension}`,
      category: "trend-improve",
      severity: "positive",
      courseId: improving.course.course.id,
      message: `Your ${dimensionLabel(improving.dimension)} performance in "${improving.course.course.name}" has improved recently.`,
      evidence: `Recent average ${round1(improving.delta)} points higher than the earlier recorded average.`,
    });
  }

  if (
    semester.tasks.totalRelevant >= MIN_TASKS_FOR_CONSISTENCY &&
    semester.tasks.completionRate !== undefined &&
    semester.tasks.completionRate >= HIGH_CONSISTENCY_THRESHOLD
  ) {
    insights.push({
      id: "consistency",
      category: "consistency",
      severity: "positive",
      message: "You're completing tasks consistently this semester.",
      evidence: `${semester.tasks.completed} of ${semester.tasks.totalRelevant} tasks completed (${round1(semester.tasks.completionRate)}%).`,
    });
  }

  if (semester.grades.entryCount > 0 && semester.grades.trend.trend === "insufficient-data") {
    insights.push({
      id: "trend-data-grades",
      category: "trend-data",
      severity: "info",
      message: "There is not enough grade history yet to determine a trend.",
      evidence: `${semester.grades.entryCount} grade ${semester.grades.entryCount === 1 ? "entry" : "entries"} recorded so far.`,
    });
  }

  return insights.sort((a, b) => SEVERITY_RANK[b.severity] - SEVERITY_RANK[a.severity]);
}
